
version: "branch-{branch}-build-nr-{build}"
skip_tags: true
environment:
  global:
    STACK_ROOT: C:\sr

build: off

install:
  - git submodule update --init --recursive
  - curl -ostack.zip -L --insecure http://www.stackage.org/stack/windows-i386
  - 7z x stack.zip stack.exe
  - set PATH=%PATH%:C:\Stack
  - echo %PATH%
  - mkdir C:\Stack
  - move stack.exe C:\Stack\
  - .\cef3-raw\scripts\setup.bat

build_script:
  - cd cef3-raw
  - .\scripts\build.bat
  - cd ..
  - stack setup --skip-msys --no-terminal > NUL
  - stack build
